name = input("Enter your name: ")
surname = input("Enter your surname:  ")
age = input("Enter your age: ")
color = input("Enter your color: ")
number = input("Enter your number")
print(name)
print(surname)
print(age)
print(color)
print(number)